### ISSUE TITLE
Add Google Maps location data import

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/covid-alert#11]
We need to allow patients to import their Google Maps data as locations in the DB.  This should help the process of inputting data to be much faster and far more accurate.

**Comment by codeboy5** [comment]
I would like to work on this

**Comment by cereallarceny** [comment]
I believe this is already being worked on by @kevmo314

**Comment by Shreyasldl** [comment]
@kevmo314 can you please confirm if you are working on the issue - would be great to connect with you and confirm - thanks

**Comment by kevmo314** [comment]
This is implemented in pr 13.

**Comment by Shreyasldl** [comment]
Thanks @kevmo314
