### ISSUE TITLE
Translation into Hindi

### ISSUE THREAD

**Issue by Shreyasldl** [OpenMined/covid-alert#18]
Hi Folks, 

The COVID - ALERT app currently works in 8 different languages. We need this to work in Hindi.  We estimate the time needed for this task would be around 60-90 minutes. Please be very sensitive to the nature of messaging - best would be to slack me "Shreyas" and align on the tone and meaning before publishing it.

thanks

**Comment by Kritikalcoder** [comment]
I'm taking this up!
