### ISSUE TITLE
Arabic body copy isn't right aligned

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/covid-alert#2]
For whatever reason, I cannot get Arabic copy in the body section to right align. Open to anyone who speaks Arabic taking this issue!

<img width="476" alt="Screen Shot 2020-03-13 at 9 33 58 PM" src="https://user-images.githubusercontent.com/1297930/76661307-05bae400-6573-11ea-8863-f3e85c5b82f5.png">

**Comment by s0l0ist** [comment]
@cereallarceny I've fixed this in my upcoming PR.

**Comment by s0l0ist** [comment]
<img width="584" alt="Fixed RTL for Arabic" src="https://user-images.githubusercontent.com/3663107/77979156-7d09ab00-72c9-11ea-8927-39965ec6435d.png">

**Comment by cereallarceny** [comment]
Great that you fixed it @s0l0ist , but until your PR has been approved, we're gonna leave this ticket open. @SETIADEEPANSHU will be responsible for reviewing that PR.  :)
