### ISSUE TITLE
Quarantine reminders | Engine : Calculating distance

### ISSUE THREAD

**Issue by Shreyasldl** [OpenMined/covid-alert#22]
Let's calculate the distance that the user moves everyday. Also, would be good to centralize this information somewhere so that we could show where they lie on the curve. Top 10% of all movers, Bottom 10% le of all movers etc.,

(Note: The location data works only if we have the "always on" permission on the app. This is the best we can do!)

**Comment by cereallarceny** [comment]
We're not doing this anymore.
