### ISSUE TITLE
Footer is on top of links in smaller phones

### ISSUE THREAD

**Issue by tcp** [OpenMined/covid-alert#6]
Either a solution with ScrollView works or we scale the screen to fit any phone size :)

**Comment by thelosergeek** [comment]
Can I work on this?
I can only contribute to the android app because I don't have MacBook for iOS app development

**Comment by IamRavikantSingh** [comment]
I would like to work on this issue.

**Comment by s0l0ist** [comment]
I've fixed this in my PR, keeping open until release.
